apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-workers
  labels:
    app: bot-workers
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bot-workers
  template:
    metadata:
      labels:
        app: bot-workers
    spec:
      containers:
      - name: bot
        image: distributed-system/bot:latest
        env:
        - name: BOT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MAIN_SERVER_URL
          value: "http://main-server-service:3001"
        - name: HEARTBEAT_INTERVAL_MS
          value: "30000"
        - name: PROCESSING_DURATION_MS
          value: "300000"
        - name: FAILURE_RATE
          value: "0.15"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import requests; requests.get('http://main-server-service:3001/healthz', timeout=5)"
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import requests; requests.get('http://main-server-service:3001/healthz', timeout=5)"
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-workers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-workers
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric based on pending jobs
  - type: Object
    object:
      metric:
        name: pending_jobs_count
      target:
        type: Value
        value: "10"
      describedObject:
        apiVersion: v1
        kind: Service
        name: main-server-service
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Min

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bot-workers-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bot-workers