global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'main-server'
    static_configs:
      - targets: ['main-server:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dashboard'
    static_configs:
      - targets: ['dashboard:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s